### ISSUE TITLE
Cannot Scroll on React-Native-Web IOS Device

### ISSUE THREAD

**Issue by BurnedChris** [TaumuLu/react-scroll-paged-view#1]
Hello,

You cannot scroll vertically on iOS browser but it is possible on the web. 
Using the React-Native-Web version! Thank you.

**Comment by TaumuLu** [comment]
> Hello,
> 
> You cannot scroll vertically on iOS browser but it is possible on the web.
> Using the React-Native-Web version! Thank you.

My local test did not find the problem you said, the ios version is 10.3+, the specific description of your version, I updated the example you can run down to see if you have the same problem
