### ISSUE TITLE
横向滑动第一次滑动的时候是预加载不行。

### ISSUE THREAD

**Issue by MichaelHao25** [TaumuLu/react-scroll-paged-view#3]
![Kapture 2019-04-19 at 16 02 44](https://user-images.githubusercontent.com/20773235/56414257-94b87100-62bc-11e9-98ac-aacf71f18650.gif)

**Comment by MichaelHao25** [comment]
看到没有后面的一屏幕是白色的。每次第一次加载都是这样的。

**Comment by TaumuLu** [comment]
> 看到没有后面的一屏幕是白色的。每次第一次加载都是这样的。

默认懒加载下一屏，但是在touchEnd的时候，有个参数isMovingRender控制在touchMove结束时加载下一页，你需要加上，我[demo](https://github.com/TaumuLu/react-scroll-paged-view/blob/master/example/app/App.js#L74)里的这行配置

**Comment by TaumuLu** [comment]
我想这里isMovingRender默认为true可能好点，但我更多的情况是需要它为false @MichaelHao25

**Comment by MichaelHao25** [comment]
已经添加了，   <WrapView
          onChange={this._onChange}
          // onResponder={this._onResponder}
          // renderHeader={this._renderTabBar}
          // renderFooter={this._renderDot}
          // tabBarPosition='top'
          // hasAnimation={false}
          // initialPage={0}
          isMovingRender
        // vertical={false}
        // initialPage={1}
        infinite
        // locked
        // autoPlay
        >
          {/* <View style={[Style.pageView, { backgroundColor: 'black' }]}>
            <Text style={Style.text}>head</Text>
            <Text style={Style.textIndex}>page {0}</Text>
            <Text style={Style.text}>foot</Text>
          </View> */}
          {pageLists.map((val, ind) => {
            return (
              <InsideScrollView
                key={ind}
                text={ind + 1}
                style={Style[`pageItem_${ind % 3}`]}
              />
            )
          })}
        </WrapView>

**Comment by MichaelHao25** [comment]
![image](https://user-images.githubusercontent.com/20773235/56416850-b289d400-62c4-11e9-9fc3-4a21d88acfa6.png)

**Comment by MichaelHao25** [comment]
![image](https://user-images.githubusercontent.com/20773235/56416867-bf0e2c80-62c4-11e9-9890-e3ea6adfb849.png)

现在我动态添加pagelists的时候，拖拽的动画也没了

**Comment by MichaelHao25** [comment]
我上图

**Comment by MichaelHao25** [comment]
@TaumuLu

**Comment by MichaelHao25** [comment]
![Kapture 2019-04-19 at 17 04 18](https://user-images.githubusercontent.com/20773235/56417002-304ddf80-62c5-11e9-8237-54ff675746b5.gif)

需求时用户打开这张页面，默认求情可能有十条数据，用户滑动到第九条的时候我就回去拉去下一页的数据

**Comment by MichaelHao25** [comment]
但是拉取的新数据就没有滑动的动画了。

**Comment by MichaelHao25** [comment]
import React, { Component } from 'react'
import {
  StyleSheet,
  Platform,
  Text,
  Dimensions,
  NativeModules,
  View,
  ScrollView,
  TouchableOpacity
} from 'react-native'
import PropTypes from 'prop-types'

import ScrollPagedView, { ViewPaged } from 'react-scroll-paged-view'
// import ScrollPagedView, { ViewPaged } from './../src'

let height = Dimensions.get('window').height
const width = Dimensions.get('window').width

if (Platform.OS === 'android') {
  height -= NativeModules.StatusBarManager.HEIGHT
}

export default class App extends Component {

  constructor(props) {
    super(props);
    this.state = {
      pageLists: ['blue', 'green', 'red',],

    }
  }
  _onChange = (currentPage, prevPage) => {
    const { pageLists } = this.state
    console.log(currentPage, prevPage);
    let length = pageLists.length;
    if (currentPage + 1 == length) {
      this.setState(prevState => {
        let temp = prevState.pageLists;
        temp.push(currentPage);
        return {
          pageLists: temp,
        }
      }
      )
    }
  }
  render() {
    const WrapView = ScrollPagedView
    // const WrapView = ViewPaged
    const { pageLists } = this.state
    console.log(pageLists);

    return (
      <View style={Style.container}>
        <WrapView
          onChange={this._onChange}
          // onResponder={this._onResponder}
          // renderHeader={this._renderTabBar}
          // renderFooter={this._renderDot}
          // tabBarPosition='top'
          // hasAnimation={false}
          // initialPage={0}
          isMovingRender
        // vertical={false}
        // initialPage={1}
        infinite
        // locked
        // autoPlay
        >
          {/* <View style={[Style.pageView, { backgroundColor: 'black' }]}>
            <Text style={Style.text}>head</Text>
            <Text style={Style.textIndex}>page {0}</Text>
            <Text style={Style.text}>foot</Text>
          </View> */}
          {pageLists.map((val, ind) => {
            return (
              <InsideScrollView
                key={ind}
                text={ind + 1}
                style={Style[`pageItem_${ind % 3}`]}
              />
            )
          })}
        </WrapView>
      </View>
    )
  }
}


class InsideScrollView extends Component {
  static contextTypes = {
    ScrollView: PropTypes.func,
  }

  render() {
    const WrapView = this.context.ScrollView || ScrollView
    const { text, style } = this.props

    return (
      <View style={{ flex: 1 }}>
        <WrapView style={{ flex: 1 }}>
          <View style={[Style.pageView, style]}>
            <Text>{text}</Text>
          </View>
        </WrapView>
      </View>
    )
  }
}

const Style = StyleSheet.create({
  container: {
    flex: 1,
    height,
    width,
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },

  pageView: {
    flex: 1,
    backgroundColor: '#F5FCFF',
    alignItems: 'center',
    paddingVertical: 20,
    justifyContent: 'space-between',
  },
  text: {
    fontSize: 40,
    color: 'white',
  },
  textIndex: {
    fontSize: 80,
    color: 'white',
  },

  pageItem_0: {
    backgroundColor: 'blue',
    height: height,
    width,
  },
  pageItem_1: {
    backgroundColor: 'green',
    height: height,
    width,
  },
  pageItem_2: {
    backgroundColor: 'red',
    height,
    width,
  },

  tabBarContainer: {
    minWidth: 50,
    minHeight: 50,
    backgroundColor: 'white',
    borderColor: '#000',
    flexDirection: 'row',
  },
  tabBarItem: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomWidth: 4,
    borderColor: 'transparent',
  },
  tabBarItemText: {
    fontSize: 18,
    color: 'gray',
  },

  dotContainer: {
    position: 'absolute',
    bottom: 80,
    left: 100,
    right: 100,
    height: 10,
    flexDirection: 'row',
  },
  dotItemView: {
    height: 10,
    width: 10,
    borderRadius: 5,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
  },
})

**Comment by MichaelHao25** [comment]
代码已经附上了。

**Comment by TaumuLu** [comment]
@MichaelHao25  已修复， 安装最新版本react-scroll-paged-view@2.2.6
